### ISSUE TITLE
tests for user routes

### ISSUE THREAD

**Issue by demadong** [mell0kat/guentherGoods#30]

**Comment by nickpalenchar** [comment]
A few errors. one is `ERRCONNECTIONREFUSED`

**Comment by nickpalenchar** [comment]
fixed previous issue, but still problematic with fetching specific users.

**Comment by nickpalenchar** [comment]
Spec _gets all users with a 200 status_ returns `404` but expects `200`. This seems to be a problem with the tests itself, not the routes.
